### ISSUE TITLE
Convert SVG command giving an error for missing viewBox

### ISSUE THREAD

**Issue by jonesaustindev** [teamairship/airfoil#31]
## Expected results

Run `airfoil convert svg` with my svg in the directory `app/assets/svg` to convert to a React Native SVG.

## Observed results

When running the command, I instead receive an error that `viewBox` was not found.

### Logs

Here is my svg:
```
<svg xmlns="http://www.w3.org/2000/svg" width="15.326" height="17.495" viewBox="0 0 15.326 17.495"><defs><style>.a{fill:#1d252c;}</style></defs><path class="a" d="M24.437,14.084V8.919l-2.369.68c-1.65.466-3.3.951-4.951,1.4-.311.1-.427.214-.427.563q.029,3.874,0,7.747a3.031,3.031,0,0,1-5.844,1.184,3.04,3.04,0,0,1,3.9-3.98c.155.058.311.117.524.214V8.356c0-.233,0-.408.311-.5q5.068-1.427,10.1-2.893c.078-.019.136-.039.233-.058,0,.117.019.194.019.272,0,3.864.019,7.708,0,11.572a3.014,3.014,0,0,1-3.184,2.99A3.041,3.041,0,0,1,23,13.657a2.825,2.825,0,0,1,.99.214A4.864,4.864,0,0,0,24.437,14.084Z" transform="translate(-10.615 -4.9)"/></svg>
```

Error received:
```
airfoil convert svg
⠋ 💾 converting svg files.../Users/austin/.nvm/versions/node/v12.18.3/lib/node_modules/@airship/airfoil/node_modules/gluegun/build/index.js:13
    throw up;
    ^

Error: viewbox not found
    at parseViewBox (/Users/austin/.nvm/versions/node/v12.18.3/lib/node_modules/@airship/airfoil/build/scripts/convertSvg.js:283:15)
    at /Users/austin/.nvm/versions/node/v12.18.3/lib/node_modules/@airship/airfoil/build/scripts/convertSvg.js:234:22
    at step (/Users/austin/.nvm/versions/node/v12.18.3/lib/node_modules/@airship/airfoil/build/scripts/convertSvg.js:33:23)
    at Object.next (/Users/austin/.nvm/versions/node/v12.18.3/lib/node_modules/@airship/airfoil/build/scripts/convertSvg.js:14:53)
    at /Users/austin/.nvm/versions/node/v12.18.3/lib/node_modules/@airship/airfoil/build/scripts/convertSvg.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/austin/.nvm/versions/node/v12.18.3/lib/node_modules/@airship/airfoil/build/scripts/convertSvg.js:4:12)
    at processConvertedTsxFile (/Users/austin/.nvm/versions/node/v12.18.3/lib/node_modules/@airship/airfoil/build/scripts/convertSvg.js:222:69)
    at /Users/austin/.nvm/versions/node/v12.18.3/lib/node_modules/@airship/airfoil/build/scripts/convertSvg.js:146:108
    at Array.map (<anonymous>)
```

## Steps to reproduce

1. Put the above svg into `app/assets/svg`
2. Run `airfoil convert svg`

**Comment by townofdon** [comment]
The `airfoil convert svg` command is using the `@svgr/cli lib` under the hood. Likely the inability to convert the viewbox is a limitation of that library.

https://react-svgr.com/docs/cli/

UPDATE - tested above SVG on https://react-svgr.com/playground/ - it works there. Looks like there's an err in the Airship code.

**Comment by townofdon** [comment]
Fixed in https://github.com/teamairship/airfoil/pull/32
