### ISSUE TITLE
Add support to check version of airfoil

### ISSUE THREAD

**Issue by jonesaustindev** [teamairship/airfoil#34]
## Expected results

Ability to check version of airfoil with `airfoil --version`

## Observed results

Received an error when trying to check the version (I'm on `0.3.0`)

### Logs

```
➜ airfoil --version
/Users/austin/.nvm/versions/node/v12.18.3/lib/node_modules/@airship/airfoil/node_modules/gluegun/build/index.js:13
    throw up;
    ^

Error: Couldn't find that command, and no default command set.
    at Command.run (/Users/austin/.nvm/versions/node/v12.18.3/lib/node_modules/@airship/airfoil/node_modules/gluegun/build/runtime/runtime-find-command.js:26:19)
    at Runtime.<anonymous> (/Users/austin/.nvm/versions/node/v12.18.3/lib/node_modules/@airship/airfoil/node_modules/gluegun/build/runtime/run.js:118:58)
    at step (/Users/austin/.nvm/versions/node/v12.18.3/lib/node_modules/@airship/airfoil/node_modules/gluegun/build/runtime/run.js:44:23)
    at Object.next (/Users/austin/.nvm/versions/node/v12.18.3/lib/node_modules/@airship/airfoil/node_modules/gluegun/build/runtime/run.js:25:53)
    at fulfilled (/Users/austin/.nvm/versions/node/v12.18.3/lib/node_modules/@airship/airfoil/node_modules/gluegun/build/runtime/run.js:16:58)
```

## Steps to reproduce

1. run `airfoil --version`

**Comment by townofdon** [comment]
The `--version` [flag](https://github.com/infinitered/gluegun/blob/master/docs/runtime.md#version) was intentionally disabled because it clashed with the `airfoil version` command (which is a [different command used for bumping the version of a React Native app](https://airfoil-docs.herokuapp.com/commands/version)).

Recommend setting a defaultCommand which looks like it can be configured to intercept the `--version` option flag: https://github.com/infinitered/gluegun/blob/master/docs/runtime.md#defaultcommand
